name: food_pick_app
description: "맛집 정보 공유 앱"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.3.4 # supabase 라이브러리
  image_picker: ^1.0.7 # 이미지 데이터 가져오기 라이브러리
  flutter_naver_map: ^1.2.1 # 네이버 지도
  geolocator: ^11.0.0 # 지오코딩 (주소<->위경도 변환)
  http: ^1.2.1 # http 요청 통신 라이브러리
  daum_postcode_search: ^0.0.2 # 다음 주소검색
  flutter_inappwebview: ^5.8.0 # 다음 주소검색 ( 웹뷰 화면 )
  intl: ^0.19.0 # DateFormat을 활용할 수 있는 라이브러리

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  assets:
    - assets/

  uses-material-design: true

